### ISSUE TITLE
Compile error on oF 0.11 due to missing boost component (/boost/interprocess)

### ISSUE THREAD

**Issue by hiroMTB** [rabbitControl/ofxRabbitControl#1]
Hello Ingo,

I noticed recent oF does not compile ofxRabbitControll.
My environment is,

macOS 10.15.7
oF 0.11
Xcode 12.4

This is the error message.
`of_v0.11.0/addons/ofxRabbitControl/src/websocketServerTransporter.h:42:10: 'boost/interprocess/streams/bufferstream.hpp' file not found`

Obviously, this is because oF does not have this component(/boost/interprocess). I can compile it by downloading it from the official boost web. (oF0.11 uses boost 1.65 and oF 0.11.2 uses boost 1.66, so it should be match I guess)

We might be able to fix it by including this component inside of this repo as you did for asio. 

Thank you for this nice addon really!

**Comment by i-n-g-o** [comment]
Hey Hiroshi,

thanks for pointing this out.
I pushed a change to avoid the use boost/interprocess/streams/bufferstream.hpp

Could you give it a try?

**Comment by hiroMTB** [comment]
Hello Ingo, thank you for your quick fix. I can confirm now it runs without /boost/interprocess/. Thanks a lot!
